import Head from "next/head";
import { Inter } from "next/font/google";
import { Row, Col, Image, Container } from "react-bootstrap";
import React from "react";
import CuisineList from "@/components/CuisineList";
// prevent font awesome icon from being extremely large
import "@fortawesome/fontawesome-svg-core/styles.css";
// Prevent fontawesome from adding its CSS since we did it manually above:
import { config } from "@fortawesome/fontawesome-svg-core";
import Introduction from "@/components/Introduction";
import FoodMenu from "@/components/FoodMenu";
config.autoAddCss = false; /* eslint-disable import/first */

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  
  return (
    <React.Fragment>
      <Head>
        <title>NeoFood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <React.Fragment>
          <Introduction/>
          <div className="mt-5"></div>
          <CuisineList/>
        </React.Fragment>
      </main>
    </React.Fragment>
  );
}
